apiVersion: v2
appVersion: "1.0"
description: Meaning full description
home: https://helm.sh/helm
maintainers:
  - email: dontcontactme@example.com
    name: Ewoud De Preester
name: fastapi
sources:
  - https://github.com/helm/helm
version: 1.0.0
